#!/usr/bin/env python3
"""Offline smoke of the actual executable. No Quick configuration or Tableau credentials."""
import hashlib
import json
import os
from pathlib import Path
import select
import subprocess
import sys
import tempfile
import time
import tomllib
import zipfile

ROOT = Path(__file__).resolve().parents[1]
EXE = Path(sys.argv[1]).resolve() if len(sys.argv)>1 else ROOT / "target/release/tabkit"
VERSION = tomllib.loads((ROOT / "Cargo.toml").read_text())["package"]["version"]
checks = []
def check(name, condition):
    if not condition:
        raise AssertionError(name)
    checks.append(name)

with tempfile.TemporaryDirectory(prefix="tabkit-smoke-") as directory:
    ws = Path(directory)
    source = (ROOT / "examples/synthetic.twb").read_bytes()
    (ws / "synthetic.twb").write_bytes(source)
    original_hash = hashlib.sha256(source).hexdigest()
    common = [str(EXE), "--workspace", str(ws), "--allow-unverified-formula-edits"]
    def call(tool, args, expected=0):
        p = subprocess.run(common + ["call", tool], input=json.dumps(args), text=True,
                           capture_output=True, timeout=10)
        if p.returncode != expected:
            raise AssertionError((tool, p.returncode, p.stdout, p.stderr))
        return json.loads(p.stdout if expected in (0, 1) else p.stderr)
    status = call("system_status", {})
    check("CLI startup and version", status["engine"] == VERSION)
    check("Base build has no native Hyper", status["hyper_compiled"] is False)
    inspection = call("workbook_inspect", {"input":"synthetic.twb", "section":"calculations"})
    check("CLI inspect returns calculation", inspection["total"] > 0)
    validated = call("workbook_validate", {"input":"synthetic.twb"})
    check("CLI validation of synthetic workbook", validated["passed"] is True)
    plan_request = json.loads((ROOT / "examples/plan.json").read_text())
    plan_request["changes"]["input_sha256"] = original_hash
    planned = call("workbook_plan", plan_request)
    applied = call("workbook_apply", {"plan":planned["output"], "expected_plan_sha256":planned["plan_sha256"], "output":"candidate.twb"})
    check("CLI plan/apply preservation", applied["byte_preservation"] == "passed")
    check("CLI original file unchanged", hashlib.sha256((ws / "synthetic.twb").read_bytes()).hexdigest() == original_hash)
    delta = call("workbook_diff", {"before":"synthetic.twb", "after":"candidate.twb"})
    check("CLI semantic delta is nonempty", len(delta["delta"]) > 0)
    suite = json.loads((ROOT / "examples/assertions.json").read_text())
    suite["input_sha256"] = applied["sha256"]
    suite["assertions"][0]["formula"] = plan_request["changes"]["operations"][0]["formula"]
    (ws / "suite.json").write_text(json.dumps(suite))
    tested = call("workbook_test", {"input":"candidate.twb", "suite":"suite.json"})
    check("CLI product assertion suite", tested["passed"] is True)
    replay = call("workbook_apply", {"plan":planned["output"], "expected_plan_sha256":planned["plan_sha256"], "output":"candidate.twb"}, 2)
    check("CLI refuses overwrite", replay["error"]["code"] == "OUTPUT_EXISTS")
    bad = subprocess.run(common + ["call","file_hash"], input='{"input":"a","input":"b"}', text=True, capture_output=True, timeout=10)
    check("CLI rejects ambiguous raw JSON", bad.returncode == 2 and json.loads(bad.stderr)["error"]["code"] == "JSON_WIRE")
    # A ZIP produced independently by Python exercises the Rust DEFLATE decoder.
    with zipfile.ZipFile(ws / "python.twbx", "w", compression=zipfile.ZIP_DEFLATED) as z:
        z.writestr("book.twb", source)
        z.writestr("asset.bin", b"preserve asset bytes")
    check("Read TWBX generated by Python", call("workbook_validate", {"input":"python.twbx"})["passed"] is True)

    with tempfile.TemporaryFile() as err:
        process = subprocess.Popen(common + ["mcp"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=err)
        pending = bytearray()
        def send(message):
            process.stdin.write(json.dumps(message).encode()+b"\n")
            process.stdin.flush()
        def receive(identifier):
            deadline = time.monotonic()+10
            while time.monotonic() < deadline:
                while b"\n" in pending:
                    line, _, rest = pending.partition(b"\n"); pending[:] = rest
                    message = json.loads(line)
                    if message.get("id") == identifier:
                        if "error" in message:
                            raise AssertionError(message)
                        return message["result"]
                ready, _, _ = select.select([process.stdout], [], [], max(0, deadline-time.monotonic()))
                if ready:
                    data = os.read(process.stdout.fileno(), 65536)
                    if not data: raise AssertionError("MCP closed stdout")
                    pending.extend(data)
                    if len(pending) > 8*1024*1024: raise AssertionError("MCP response exceeded test bound")
            raise AssertionError("MCP response timeout")
        try:
            send({"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-03-26","capabilities":{},"clientInfo":{"name":"tabkit-offline-smoke","version":"1"}}})
            init = receive(1)
            check("MCP initialize", init["serverInfo"]["version"] == VERSION)
            send({"jsonrpc":"2.0","method":"notifications/initialized"})
            send({"jsonrpc":"2.0","id":2,"method":"tools/list","params":{}})
            tools = receive(2)["tools"]
            names = {tool["name"] for tool in tools}
            check("MCP exposes REST, Hyper and lineage tools", len(names)==len(tools) and {"tableau_publish","tableau_explore","hyper_query","workbook_lineage_gaps"}.issubset(names))
            send({"jsonrpc":"2.0","id":3,"method":"tools/call","params":{"name":"system_status","arguments":{}}})
            result = receive(3)
            check("MCP tool dispatch", not result.get("isError",False) and json.loads(result["content"][0]["text"])["engine"] == VERSION)
            send({"jsonrpc":"2.0","id":4,"method":"tools/call","params":{"name":"workbook_validate","arguments":{"input":"candidate.twb"}}})
            result = receive(4)
            check("MCP validates actual CLI-produced candidate", not result.get("isError",False) and json.loads(result["content"][0]["text"])["passed"] is True)
            process.stdin.close()
            check("MCP clean EOF shutdown", process.wait(timeout=10) == 0)
        finally:
            if process.poll() is None:
                process.kill(); process.wait(timeout=5)

report = {"passed":len(checks),"failed":0,"checks":checks,
          "scope":"macOS arm64 base release executable; synthetic workbooks; independent stdio client, not the Amazon Quick UI",
          "not_run":["live Tableau","corporate OAuth/PAT","native Hyper","Windows"]}
(ROOT / "reports/smoke.json").write_text(json.dumps(report,indent=2)+"\n")
print(json.dumps(report,indent=2))
